version: 2
jobs:
  test-python3:
    docker:
      - image: circleci/python:3
    working_directory: ~/zipload
    steps:
      - checkout
      # Let's install the dependencies
      - run:
          name: Install Dependencies
          command: |
            poetry install
      
      # Save's the specified path as a cache. This is the path Poetry uses to install the dependencies
      # So if you don't install anything new, this folder won't change and the cache will be effective
      - save_cache:
          key: deps-{{ checksum "poetry.lock" }}
          paths: 
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Lint
          command: |
            poetry run pylint *.py

      - run:
          name: Run tests
          command: |
            poetry run pytest

workflows:
  version: 2
  build:
    jobs:
      - test-python3
